import type { Metadata } from "next";
import "./globals.css";

// é a estrutura do head
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//Esse é o layout principal, caso queira colocar algo que fique em todas as paginas este é o local
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>{children}</body>
    </html>
  );
}
